### ISSUE TITLE
UMF/Opengraph canvas doesn't work after user visiting other menus

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/essencia#12]
Test Case:

1.  Visit the dashboard and see the detail view of a practice (to let the canvas is loaded first)
2.  Switch to the Practice Composer
3.  Open any practices or processes, it wouldn't be opened.

Solution:

1. Launch a new clean web browser (or tab) for Practice Composer
2. Find the cause (maybe namespace or dirty javascript object) and fix it.

**Comment by jinyoung** [comment]
The reason why it can't create a new canvas is due to the bug of the Raphael engine.

```
Error:  : Cannot read property 'x' of undefined. Error when to intialize the faceHelper [org_uengine_modeling_Canvas]. Detail error message is  : Cannot read property 'x' of undefined : Stack is TypeError: Cannot read property 'x' of undefined
    at Function.R._engine.create (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:5030:20)
    at new R (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:272:47)
    at new OG.renderer.RaphaelRenderer (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:18260:19)
    at new OG.graph.Canvas (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:32796:34)
    at Object.load (http://localhost:8080/dwr/metaworks/org/uengine/modeling/Canvas.ejs.js:51:23)
    at Object.org_uengine_modeling_Canvas (http://localhost:8080/dwr/metaworks/org/uengine/modeling/Canvas.ejs.js:20:20)
    at eval (eval at <anonymous> (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:407:25), <anonymous>:1:1)
    at Metaworks3.loadFaceHelper (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:407:25)
    at Metaworks3.onLoadFaceHelperScript (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:530:15)
    at Metaworks3.onLoadFaceHelperScript (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:565:14)
    at Function.R._engine.create (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:5030:20)
    at new R (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:272:47)
    at new OG.renderer.RaphaelRenderer (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:18260:19)
    at new OG.graph.Canvas (http://localhost:8080/lib/opengraph/OpenGraph-0.1.2-SNAPSHOT.js:32796:34)
    at Object.load (http://localhost:8080/dwr/metaworks/org/uengine/modeling/Canvas.ejs.js:51:23)
    at Object.org_uengine_modeling_Canvas (http://localhost:8080/dwr/metaworks/org/uengine/modeling/Canvas.ejs.js:20:20)
    at eval (eval at <anonymous> (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:407:25), <anonymous>:1:1)
    at Metaworks3.loadFaceHelper (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:407:25)
    at Metaworks3.onLoadFaceHelperScript (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:530:15)
    at Metaworks3.onLoadFaceHelperScript (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:565:14)
    at Metaworks3.loadFaceHelper (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:433:14)
    at Metaworks3.onLoadFaceHelperScript (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:530:15)
    at Metaworks3.onLoadFaceHelperScript (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:565:14)
    at MetaworksService.__showResult (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:5447:8)
    at callback (http://localhost:8080/dwr/metaworks/scripts/metaworks.js:5504:25)
    at Object.handleCallback (http://localhost:8080/dwr/engine.js:845:31)
    at eval (eval at <anonymous> (http://localhost:8080/dwr/engine.js:584:12), <anonymous>:346:3)
    at eval (eval at <anonymous> (http://localhost:8080/dwr/engine.js:584:12), <anonymous>:347:3)
    at Object.dwr.engine._eval (http://localhost:8080/dwr/engine.js:584:12)
    at Object.stateChange (http://localhost:8080/dwr/engine.js:1632:20)
```

a bug is hiding inside this code:

```
    R._engine.create = function () {
        var con = R._getContainer.apply(0, arguments),
            container = con && con.container,
            x = con.x,  <---- con is null
            y = con.y,
            width = con.width,
            height = con.height;
```

**Comment by jinyoung** [comment]
http://stackoverflow.com/questions/13992972/how-to-create-a-authentication-token-using-java

1. use the SecureRandom for generating an access token.
1. when a user logs in, a new access token is generated.
1. store the token in the server side to compare with the token web page sends to the server.
1. access token must be expired after a while or when a user logs in again.
